export const users = [
  { id: 1, name: "John Doe", age: 30 },
  { id: 2, name: "Jane Smith", age: 25 },
  { id: 3, name: "Alice Johnson", age: 28 },
  { id: 4, name: "Bob Brown", age: 35 },
  { id: 5, name: "Charlie Davis", age: 22 },
  { id: 6, name: "Emily Wilson", age: 27 },
  { id: 7, name: "Frank Miller", age: 31 },
  { id: 8, name: "Grace Lee", age: 26 },
  { id: 9, name: "Henry Taylor", age: 29 },
  { id: 10, name: "Isabella Anderson", age: 24 },
  { id: 11, name: "John Doe", age: 30 },
  { id: 12, name: "Jane Smith", age: 25 },
  { id: 13, name: "Alice Johnson", age: 28 },
  { id: 14, name: "Bob Brown", age: 35 },
  { id: 15, name: "Charlie Davis", age: 22 },
  { id: 16, name: "Emily Wilson", age: 27 },
  { id: 17, name: "Frank Miller", age: 31 },
  { id: 18, name: "Grace Lee", age: 26 },
  { id: 19, name: "Henry Taylor", age: 29 },
  { id: 20, name: "Isabella Anderson", age: 24 },
  { id: 21, name: "Frank Miller", age: 31 },
  { id: 22, name: "Grace Lee", age: 26 },
  { id: 23, name: "Henry Taylor", age: 29 },
  { id: 24, name: "Isabella Anderson", age: 24 },
];
